// <auto-generated />
namespace EC.Escola.Acesso_Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MDisc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MDisc));
        
        string IMigrationMetadata.Id
        {
            get { return "202209061801073_MDisc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
