// <auto-generated />
namespace EC.Escola.Acesso_Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MigNotas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigNotas));
        
        string IMigrationMetadata.Id
        {
            get { return "202209062056121_MigNotas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
